apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "A6u55ikzCwObh1w1Uwag8c7E3CY78Ej5TpbWCNYcxsU5Hx/1B91uCpsHIqOJ85YY\n++fvuVpZ/Eb9QYRO8mWE+vDnl8Sr0gFtL+5+PpV2LVI/UTnBc29/Jh89vPPxBQra\nRkdqDTz9o8hKCe88YBvmolPvgs/57hWi3CN3aENB00Q="
