apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "Uxb829wDNfHNkWSi2fx8CoD33QJDJCE0RORpXbu7mHfT/aJOMzq1EgjTSlEQ89Mc\nhGu9NKjjoO3b34QCWZ+F3/R25hlZWNOFS6alOyG6CvA5sBVXk9yjC1Lxaq+nwmIY\nmdq3d48lwjqsL8wcHca+61kvw56fiXe++I0AQcalAd0="
